name: Deploy Edge Functions

on:
  push:
    branches: [staging]
    tags: ['v*.*.*']

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1

      - name: Deploy edge functions
        run: supabase functions deploy --project-ref yevpbrlirmpnqefirbur
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
